{% set name = "xcollection" %}
{% set version = "2021.12.23" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xcollection-{{ version }}.tar.gz
  sha256: 7865549a0d53380e3a09070ce4ddd8768c61d19125904e518766697d3cb6991a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - pydantic
    - python >={{ python_min }}
    - toolz
    - xarray

test:
  imports:
    - xcollection
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/NCAR/xcollection
  summary: Extends xarray's data model to be able to handle a dictionary of xarray datasets.
  dev_url: https://github.com/NCAR/xcollection
  doc_url: https://xcollection.readthedocs.io
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - andersy005
    - jukent
    - kmpaul
    - mgrover1
